### ISSUE TITLE
Unhandled python exception in notification callback

### ISSUE THREAD

**Issue by ghost** [dyrnade/collectd-notify-slack-plugin#1]
I'm seeing the below error in collectd.log. Tried adding restore_sigchild, didn't help.

Any ideas?

[2017-02-09 18:56:26] [error] Unhandled python exception in notification callback: IOError: [Errno 10] No child processes
[2017-02-09 18:56:26] [error] Unhandled python exception in notification callback: IOError: [Errno 10] No child processes
[2017-02-09 18:56:26] [error] Unhandled python exception in notification callback: IOError: [Errno 10] No child processes
[2017-02-09 18:56:26] [error] Unhandled python exception in notification callback: IOError: [Errno 10] No child processes

Stack trace:

[2017-02-09 19:17:35] [error] Unhandled python exception in notification callback: IOError: [Errno 10] No child processes
[2017-02-09 19:17:35] [error] Traceback (most recent call last):
[2017-02-09 19:17:35] [error]   File "/etc/collectd/collectd-notify-slack-plugin/slack_plugin.py", line 42, in slack_notification
    send_to_slack(message)
[2017-02-09 19:17:35] [error]   File "/etc/collectd/collectd-notify-slack-plugin/slack_plugin.py", line 28, in send_to_slack
    sc = SlackClient(slacktoken)
[2017-02-09 19:17:35] [error]   File "/usr/local/lib/python2.7/dist-packages/slackclient/_client.py", line 28, in __init__
    self.server = Server(self.token, False)
[2017-02-09 19:17:35] [error]   File "/usr/local/lib/python2.7/dist-packages/slackclient/_server.py", line 27, in __init__
    self.api_requester = SlackRequest()
[2017-02-09 19:17:35] [error]   File "/usr/local/lib/python2.7/dist-packages/slackclient/_slackrequest.py", line 22, in __init__
    "system": "{0}/{1}".format(platform.system(), platform.release())
[2017-02-09 19:17:35] [error]   File "/usr/lib/python2.7/platform.py", line 1286, in system
    return uname()[0]
[2017-02-09 19:17:35] [error]   File "/usr/lib/python2.7/platform.py", line 1253, in uname
    processor = _syscmd_uname('-p','')
[2017-02-09 19:17:35] [error]   File "/usr/lib/python2.7/platform.py", line 988, in _syscmd_uname
    rc = f.close()
[2017-02-09 19:17:35] [error] IOError: [Errno 10] No child processes

**Comment by dyrnade** [comment]
Sorry for the delay. I will have a look at that, since i dont use this anymore. I will let you know. Thanks for the feedback.

**Comment by dyrnade** [comment]
Thanks for your contribution. Fixed the problem. @son1cc
